### PR TITLE
Landing Page Frontend Complete

### PR DESCRIPTION
**Pull request by Hemant2335**
## Related Issue
I have a Created  a New Landing Page Which is Fully responsive other than one thing the menu doesn't work in mobile mode.
which i would love to do in next issue.

Closes: #19 

## Description of Changes

The Changes are
-> The Pages section has got new Page folder named (Landing Page)
-> Where I have Created some new Components like navbar , about , homebanner , contact , deskmenu , wrapper
-> these are all independent components from rest of the project

- [x ] My code adheres to the established style guidelines of this project.
- [x ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ x] My changes have not introduced any new warnings.

## Screenshots

https://github.com/akashgreninja/Doggonation/assets/85656999/82ca6392-0e93-42eb-9976-ad332c948f2f

I have provided the video of landing page , if any suggestions please let me know

Thank you

### CODE REVIEW

**Review by akashgreninja — APPROVED** [review]
@2deadmen Please review the changes asap

**Comment by akashgreninja** [comment]
@Hemant2335 i see you have made changes and have pushed it  please can you share some ss I have seen all the commits you have worked hard on this I just want to verify  if possible can you attach the ss of the new changes?

**Comment by Hemant2335** [comment]
Yaa But I have already uploaded the video

Here some ss

Screenshot (77)
Screenshot (76)
Screenshot (80)
Screenshot (79)
Screenshot (78)

**Comment by Hemant2335** [comment]
here the ss of new Nav

Attached
Screenshot (81)

**Comment by akashgreninja** [comment]
@EffDuBois Please review and pull asap

**Comment by EffDuBois** [comment]
@Hemant2335 hey, being a social media website this landing page doesn't work well with our ux. But this is a great about-us page, so could you route it to our about us page replacing the current one. I'll assign you the consequent issues of making the donation button and related issues as well.

**Comment by Hemant2335** [comment]
Yaa ok that is also a good option 

I am creating  a new issue please assign it to me

**Comment by Hemant2335** [comment]
I have successfully created a new donation page 

here some ss

Screenshot (83)
Screenshot (82)
Screenshot (84)


And if you don't want sidebar on the page please let me know

Thankyou

**Pull request merged**
