### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by raunakcode03**
## Related Issue

Closes: #[9]

## Checklist:

- [x] Make it more professional
- [x] Change The logo
- [x]  Add Open Source Contribution
- [x]  Correcting Terms and elaborate it
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot
) | Updated screenshot |
Updated 1
updated 2

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by EffDuBois** [comment]
What is the source of the new logo

**Comment by raunakcode03** [comment]
> What is the source of the new logo

Canva

**Comment by EffDuBois** [comment]
@raunakcode03 hey can you use the original logo itself. As it's original and copyright free.
Do that and I'll pull the commit

**Comment by raunakcode03** [comment]
> @raunakcode03 hey can you use the original logo itself. As it's original and copyright free.
> Do that and I'll pull the commit

The logo that you guys used that one ?

**Comment by EffDuBois** [comment]
> > @raunakcode03 hey can you use the original logo itself. As it's original and copyright free.
> > Do that and I'll pull the commit
> 
> The logo that you guys used that one ?

Yes

**Comment by raunakcode03** [comment]
> > > @raunakcode03 hey can you use the original logo itself. As it's original and copyright free.
> > > Do that and I'll pull the commit
> > 
> > 
> > The logo that you guys used that one ?
> 
> Yes

done .Add Badges also that were there

**Review by EffDuBois — APPROVED** [review]

**Pull request merged**
